name: Unit tests
on:
  push:
    branches: [master]
jobs:
  job1:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Environment configuration
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Running tests 🧪
        id: test-running-id
        run: |
          python -m unittest discover -s tests -p 'test*.py' -v
        env:
          ENVIRONMENT: test
          
